import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import { Toaster } from 'react-hot-toast'
import { AuthContextProvider } from './context/authContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Luco's store",
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Nav />
          {children}
          <Toaster />
        </AuthContextProvider>
      </body>
    </html>
  )
}
